source 'https://github.com/CocoaPods/Specs.git'
source 'git@codeup.aliyun.com:xhey/ios/XHSpecs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

require_relative 'react-native/node_modules/react-native/scripts/react_native_pods'
require_relative 'react-native/node_modules/@react-native-community/cli-platform-ios/native_modules'

# 3.0.205版本：适配Xcode15，最低版本改为13.4
platform :ios, '13.0'
use_frameworks! :linkage => :static

# 设置 Swift 版本
swift_version = '5.0'

use_react_native!(
    :path => 'react-native/node_modules/react-native'
)

target 'react-native-link-lib-sample' do

  # Pods for react-native-link-lib-sample
  prefix = 'react-native/node_modules'
  pod 'react-native-link-lib', :path => "#{prefix}/react-native-link-lib"

  
  # 为所有 Pod 设置 Swift 版本
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
    
    react_native_post_install(installer)
  end
end

